### ISSUE TITLE
Problems running dafga_otus.py

### ISSUE THREAD

**Issue by kjp2** [outbig/DAFGA#1]
Hei,
I wanted to try your program, so I downloaded and installed it and tried running it with the test files.
## However, when running dafga_otus.py I get the following error message:

Invalid command line
Option --cluster_fast is invalid
For list of command-line options use --help.

Done

Traceback (most recent call last):
  File "/usr/local/bin/dafga_otus.py", line 156, in <module>
    preclstr_otu,pre_rep_otu = parse_usearch(preclstr,"precluster")
  File "/usr/local/bin/dafga_otus.py", line 105, in parse_usearch
    with open(base+"_OTUs.txt","w") as otu, open(clstr,"r") as cluster:
## IOError: [Errno 2] No such file or directory: '/home/Downloads/DAFGA-master/test/otus/preclustering/preclstr_0.97.uc'

I don't really know what to make of this, seems to be a problem with usearch? I have usearch installed and have also used the uclust in qiime without any problems.
Do you have an idea what might be wrong?

BR,
Katharina

**Comment by outbig** [comment]
Hi Katharina,

Thanks for your interest in DAFGA. As you said, the error happend when 
USEARCH was executed. Is USEARCH binary in a directory specified in your 
PATH variable?

Best,
Yongkyu

**Comment by kjp2** [comment]
Hei,
thank you for your answer. Usearch should be in directory that is referred to in PATH, at least I can call usearch from the console individually.Does DAFGA require a specific version of usearch? For qiime I have usearch v5.2.236 installed.
BR,Katharina

```
tiistai 15. maaliskuuta 2016 16.42 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi Katharina,

Thanks for your interest in DAFGA. As you said, the error happend when 
USEARCH was executed. Is USEARCH binary in a directory specified in your 
PATH variable?

Best,
Yongkyu

**Comment by outbig** [comment]
Hi Katharina,

I would recommend to install  the version higher than v7.0. DAFGA run 
USEARCH using cluster_fast command, but the version you have has no this 
command. Please don't hesitate to contact if you have any other 
questions or help.

Best,
Yongkyu

**Comment by kjp2** [comment]
Hei,
yes, I updated usearch and got that part of the program running.Now I am stuck with dafga_taxonomy.py.I get an error:Xlib:  extension "XInputExtension" missing on display ":13.0".
Traceback (most recent call last):
  File "/usr/local/bin/dafga_taxonomy.py", line 170, in <module>
    qt = otu_table()
NameError: name 'otu_table' is not defined

But I am not sure why this is coming up. Maybe I have another package missing? Obviously it cannot use the otu_table() 
It generated sequence_BLASTP.xml, sequence_ref.phr, _.pin,_.psq, sequence_taxa_assignment.txt and align_prof.pdf before stopping.
Do you have any idea on this?
BR,Katharina

```
keskiviikko 16. maaliskuuta 2016 14.14 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi Katharina,

I would recommend to install the version higher than v7.0. DAFGA run 
USEARCH using cluster_fast command, but the version you have has no this 
command. Please don't hesitate to contact if you have any other 
questions or help.

Best,
Yongkyu

**Comment by outbig** [comment]
Hi,

The function named otu_table() is missing in the dafga_taxonomy.py by 
mistake. I will fix it as soon as possible, but it may take few days 
because I am busy now for doing something else. I am very sorry for 
inconvenience.

Best,
Yongkyu

**Comment by kjp2** [comment]
Hei,
no problem, just edit the script whenever you have the time.
BR,Katharina

```
keskiviikko 16. maaliskuuta 2016 16.08 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi,

The function named otu_table() is missing in the dafga_taxonomy.py by 
mistake. I will fix it as soon as possible, but it may take few days 
because I am busy now for doing something else. I am very sorry for 
inconvenience.

Best,
Yongkyu

**Comment by kjp2** [comment]
Hei,
did you get a chance yet to fix the taxonomy-script?

BR,Katharina

```
keskiviikko 16. maaliskuuta 2016 16.08 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi,

The function named otu_table() is missing in the dafga_taxonomy.py by 
mistake. I will fix it as soon as possible, but it may take few days 
because I am busy now for doing something else. I am very sorry for 
inconvenience.

Best,
Yongkyu

**Comment by outbig** [comment]
Hi,

It will be done in two days.

Sorry,
Yongkyu

**Comment by outbig** [comment]
Hi Katharina,

Please find attached modified dafga_taxonomy.py. If you have QIIME 
installed, it should work. But in this version, you need to provide a 
mapping file to execute. Then it will generate otu_table.biom & 
rep_phyltree.tre, which can be used as an input for diversity analysis 
in QIIME pipeline. Sorry for delay again. I have noticed that QIIME made 
many updates. As soon as possible, I am also going to make an official 
update which will perfectly compatible with the most recent QIIME. If 
you have any other problems, don't hesitate to contact me.

BR,
Yongkyu

**Comment by kjp2** [comment]
Hei,
I think you forgot the attachment (at least I did not get any).
BR,Katharina

```
perjantai 1. huhtikuuta 2016 13.03 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi Katharina,

Please find attached modified dafga_taxonomy.py. If you have QIIME 
installed, it should work. But in this version, you need to provide a 
mapping file to execute. Then it will generate otu_table.biom & 
rep_phyltree.tre, which can be used as an input for diversity analysis 
in QIIME pipeline. Sorry for delay again. I have noticed that QIIME made 
many updates. As soon as possible, I am also going to make an official 
update which will perfectly compatible with the most recent QIIME. If 
you have any other problems, don't hesitate to contact me.

BR,
Yongkyu

**Comment by outbig** [comment]
Sorry. It's a mistake. Unfortunately, the file is in the workstation at office. I will send it next Monday. 
Cheers,Yongkyu

-------- Original message --------

**Comment by outbig** [comment]
Please find attached.

BR,
Yongkyu

**Comment by outbig** [comment]
Hi Katharina,

I have sent the modified dafga_taxonomy.py as attachment, but it seems 
not attached through the github issues communication. Please give me 
your email.

BR,
Yongkyu

**Comment by kjp2** [comment]
Hei,
my mail is katy_palmer@yahoo.com.
BR,Katharina

```
maanantai 4. huhtikuuta 2016 13.04 Yongkyu Kim <notifications@github.com> kirjoitti:
```

 Hi Katharina,

I have sent the modified dafga_taxonomy.py as attachment, but it seems 
not attached through the github issues communication. Please give me 
your email.

BR,
Yongkyu

**Comment by Madegwa** [comment]
I am experiencing the same problem. Were the scripts updated?
