### ISSUE TITLE
dafga_otus.py, KeyError on test data

### ISSUE THREAD

**Issue by MichalOskiera** [outbig/DAFGA#5]
Hi, 
After pick_otus in dafga_otus.py. I get an error:

   ...Create OTU table...
Traceback (most recent call last):
  File "/usr/local/bin/dafga_otus.py", line 160, in <module>
    OTU_table(preclstr_otu,clstr_otu)
  File "/usr/local/bin/dafga_otus.py", line 135, in OTU_table
    seqOTU.write("\t"+preclstr_dict[value])
KeyError: 'Cluster1325'

Any ideas? 
Greetings

**Comment by huanqinli** [comment]
Hi, I also encountered the same problem as you. Have you found a solution? Thank you

**Comment by huanqinli** [comment]
@MichalOskiera
